[package]
name = "gtmintel"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
askama = { version = "0.12", features = ["with-axum"] }
askama_axum = "0.4" # Provides Askama extractor/response for Axum
tower = "0.4"
tower-http = { version = "0.5", features = ["fs", "trace"] } # For static files & tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1.0", features = ["derive"] } # Optional but likely needed later
# Add other dependencies as needed (e.g., for database, scraping)
